CREATE TABLE IF NOT EXISTS `bills` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `identifier` VARCHAR(255) NOT NULL,
  `sender` VARCHAR(255) NOT NULL,
  `amount` INT(11) NOT NULL,
  `reason` VARCHAR(255) NOT NULL,
  `state` TINYINT(1) NOT NULL DEFAULT '0',
  `date_issued` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
